# Generated by Django 5.0 on 2024-08-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
