# Generated by Django 5.1 on 2024-09-22 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_table1_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
