# Generated by Django 5.1 on 2024-09-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_table1_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
