# Generated by Django 5.1 on 2024-09-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_table1_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
